export const books = [
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishedYear: 1960,
    genre: "Fiction",
    price: 18.99,
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    publishedYear: 1949,
    genre: "Dystopian",
    price: 14.99,
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishedYear: 1925,
    genre: "Fiction",
    price: 12.99,
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishedYear: 1813,
    genre: "Romance",
    price: 10.99,
  },
  {
    id: 5,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishedYear: 1951,
    genre: "Fiction",
    price: 15.99,
  },
  {
    id: 6,
    title: "Moby-Dick",
    author: "Herman Melville",
    publishedYear: 1851,
    genre: "Adventure",
    price: 17.99,
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    publishedYear: 1869,
    genre: "Historical Fiction",
    price: 22.99,
  },
  {
    id: 8,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publishedYear: 1866,
    genre: "Psychological Fiction",
    price: 19.99,
  },
  {
    id: 9,
    title: "Brave New World",
    author: "Aldous Huxley",
    publishedYear: 1932,
    genre: "Dystopian",
    price: 16.99,
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publishedYear: 1954,
    genre: "Fantasy",
    price: 29.99,
  },
  {
    id: 11,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishedYear: 1937,
    genre: "Fantasy",
    price: 15.99,
  },
  {
    id: 12,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    publishedYear: 1953,
    genre: "Dystopian",
    price: 13.99,
  },
  {
    id: 13,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    publishedYear: 1847,
    genre: "Gothic Fiction",
    price: 14.99,
  },
  {
    id: 14,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    publishedYear: 1847,
    genre: "Romance",
    price: 12.99,
  },
  {
    id: 15,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publishedYear: 1890,
    genre: "Philosophical Fiction",
    price: 11.99,
  },
  {
    id: 16,
    title: "Dracula",
    author: "Bram Stoker",
    publishedYear: 1897,
    genre: "Horror",
    price: 13.99,
  },
  {
    id: 17,
    title: "The Odyssey",
    author: "Homer",
    publishedYear: -700,
    genre: "Epic",
    price: 19.99,
  },
  {
    id: 18,
    title: "The Iliad",
    author: "Homer",
    publishedYear: -750,
    genre: "Epic",
    price: 18.99,
  },
  {
    id: 19,
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    publishedYear: 1880,
    genre: "Philosophical Fiction",
    price: 21.99,
  },
  {
    id: 20,
    title: "Les Misérables",
    author: "Victor Hugo",
    publishedYear: 1862,
    genre: "Historical Fiction",
    price: 24.99,
  },
  {
    id: 21,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    publishedYear: 1877,
    genre: "Romance",
    price: 22.99,
  },
  {
    id: 22,
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    publishedYear: 1844,
    genre: "Adventure",
    price: 23.99,
  },
  {
    id: 23,
    title: "Frankenstein",
    author: "Mary Shelley",
    publishedYear: 1818,
    genre: "Horror",
    price: 14.99,
  },
  {
    id: 24,
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    publishedYear: 1967,
    genre: "Magical Realism",
    price: 18.99,
  },
  {
    id: 25,
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    publishedYear: 1605,
    genre: "Adventure",
    price: 25.99,
  },
  {
    id: 26,
    title: "Ulysses",
    author: "James Joyce",
    publishedYear: 1922,
    genre: "Modernist Fiction",
    price: 26.99,
  },
  {
    id: 27,
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    publishedYear: 1320,
    genre: "Epic Poetry",
    price: 27.99,
  },
  {
    id: 28,
    title: "The Stranger",
    author: "Albert Camus",
    publishedYear: 1942,
    genre: "Existential Fiction",
    price: 15.99,
  },
  {
    id: 29,
    title: "Meditations",
    author: "Marcus Aurelius",
    publishedYear: 180,
    genre: "Philosophy",
    price: 17.99,
  },
  {
    id: 30,
    title: "The Art of War",
    author: "Sun Tzu",
    publishedYear: -500,
    genre: "Military Strategy",
    price: 14.99,
  },
  {
    id: 31,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    publishedYear: 2011,
    genre: "History",
    price: 22.99,
  },
  {
    id: 32,
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    publishedYear: 2015,
    genre: "Future Studies",
    price: 23.99,
  },
  {
    id: 33,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    publishedYear: 2012,
    genre: "Self-Help",
    price: 16.99,
  },
  {
    id: 34,
    title: "Atomic Habits",
    author: "James Clear",
    publishedYear: 2018,
    genre: "Self-Help",
    price: 20.99,
  },
  {
    id: 35,
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    publishedYear: 2011,
    genre: "Psychology",
    price: 21.99,
  },
  {
    id: 36,
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    publishedYear: 1989,
    genre: "Self-Help",
    price: 19.99,
  },
  {
    id: 37,
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    publishedYear: 1936,
    genre: "Self-Help",
    price: 15.99,
  },
  {
    id: 38,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    publishedYear: 1997,
    genre: "Personal Finance",
    price: 14.99,
  },
  {
    id: 39,
    title: "The Lean Startup",
    author: "Eric Ries",
    publishedYear: 2011,
    genre: "Business",
    price: 24.99,
  },
  {
    id: 40,
    title: "Zero to One",
    author: "Peter Thiel",
    publishedYear: 2014,
    genre: "Business",
    price: 20.99,
  },
  {
    id: 41,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    publishedYear: 2020,
    genre: "Finance",
    price: 18.99,
  },
  {
    id: 42,
    title: "The Alchemist",
    author: "Paulo Coelho",
    publishedYear: 1988,
    genre: "Adventure",
    price: 14.99,
  },
  {
    id: 43,
    title: "The Road",
    author: "Cormac McCarthy",
    publishedYear: 2006,
    genre: "Post-Apocalyptic Fiction",
    price: 16.99,
  },
  {
    id: 44,
    title: "The Book Thief",
    author: "Markus Zusak",
    publishedYear: 2005,
    genre: "Historical Fiction",
    price: 17.99,
  },
];
